// DO NOT EDIT THIS FILE!
#include "task1.hpp"
#include "task2.hpp"
#include "task1.hpp"

#include <iostream>

int main() {
    Vector<int> vec(10);
    /*
        imagine some work with this vector
    */
    std::cout << foo() << std::endl;
    std::cout << foo2() << std::endl;
    std::cout << vec.size() << std::endl;
}
